### ISSUE TITLE
[1.12.2] Crash when summoning

### ISSUE THREAD

**Issue by GWSheridan** [Shinoow/By-The-Gods#4]
When summoning Cthulhu he insta killed me lol but also crashed the game

Crash Log: https://pastebin.com/HWdUeeez

Versions
By The Gods: 1.0.1
MC: 1.12.2
Forge: 14.23.1.2586

**Comment by VioletWyvern** [comment]
This is not a bug, because this is meant to be, summoning all these old ones will instantly kill the player and crashing the game (Especially the Azathoth, it not only crash the game, it also deleting all your world files in your save folder)   

Beside of this,  I think this mod was went a little bit too far....(What next? An old ones can uninstall your Minecraft from your computer?  Or can deleting your Minecraft account?)

**Comment by ChakatStormCloud** [comment]
Umm, No, reading through the source code, the crash is absolutely unintentional.
it's a concurrent modification exception from trying to remove the potion effects on the player when it tries to kill them.

**Comment by Zero5192** [comment]
Hey can you help me how can I summon Great Old Ones ???

**Comment by Zero5192** [comment]
Or can you give me an rirtuals images pls

**Comment by ChakatStormCloud** [comment]
> Hey can you help me how can I summon Great Old Ones ???
> Or can you give me an rirtuals images pls

1. you shouldn't be posting this inside an existing issue
2. you shouldn't be asking questions on an issue tracker normally
3. WARNING doesn't actually summon anything, they all just either blow up/kill/poison/kill/erase the person who did the ritual or kill everything on the server.
4. dig through the code here, you can find all the recipes pretty easy
5. here:

```
Azathoth:       N,S: Obsidian blocks,  E,W: Ender Eyes
Cthulhu:        N, S: Beds,             E, W: Water Buckets
Dagon:          N, S: Any fish,         E, W: Prismarine shards
YogSothoth:     N, S: Clocks,           E, W: Any vanilla door
Hastur:         N, E, S, W: 4 Name tags called "Hastur"
Nyarlathotep:   N, E, S, W: TNT.
ShubNiggurath:  N, E, S, W: any wool

Effects:

Cthulhu: Inventory deleted + death + crash
Dagon: Death + crash + prismarine structure (probably won't run since the kill util will crash the game first)
YogSothoth: Death + crash
Hastur: Explosion + Death + crash
Nyarlathotep:  Super TNT everywhere ---NO CRASH OR INSTA DEATH----
ShubNiggurath: Death + crash + random sheep and evil sheep everywhere

Azathoth: (hoo boy)
First, it sets the world to hard difficulty and hardcore mode (singleplayer locks on death, multiplayer bans on death)
Next, on a server, it sets all the world files to delete on exit (not sure if this works when it crashes)
Then it tries to kill every single living entity and crashes because of the potion shit like everything else.
if it didn't crash, it would then force shutdown the game.
```
