### ISSUE TITLE
Feature suggestion Minetweaker support

### ISSUE THREAD

**Issue by Tarod7** [Shinoow/By-The-Gods#5]
Allow minetweaker to change summoning rituals

**Comment by Shinoow** [comment]
Currently the CraftTweaker integration in AbyssalCraft Integration process the script tasks too early, leading to it modifying the rituals before they're registered (which in turn does nothing, as you can't modify something that doesn't exist yet). This will be fixed the next time I release an update for that mod (which I plan on doing soon).

**Comment by Shinoow** [comment]
The adjustments to properly modify the rituals added by this mod is in! File available at https://minecraft.curseforge.com/projects/abyssalcraft-integration/files/2573661

**Comment by Tarod7** [comment]
Thanks!

**Comment by Zero5192** [comment]
Shinoow , can you help me ? How can I summon a Great Old Ones
