### ISSUE TITLE
How to summon Great Old Ones

### ISSUE THREAD

**Issue by Zero5192** [Shinoow/By-The-Gods#6]
#### Intro:

This template is intended for bug reports. If you're not posting a bug report, you can remove all of the text that makes up the template. If you are reporting a bug, and you choose not to use this template, your issue will be closed. You may now delete this section and continue on with the report.

#### Description:

If this bug occurs in a modpack, please report this to the modpack author. Otherwise delete this line and add your description here.

#### Crash report:

[pastebin/gist/etc link here if the bug results in a crash, leave line empty otherwise]

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft:
- Forge:
- By The Gods:
- AbyssalCraft:

#### Latest log file for when the issue was present:

[pastebin/gist/etc link here]

**Comment by Zero5192** [comment]
How to summon Great Old Ones pls

**Comment by Shinoow** [comment]
As the mod page states, the rituals for summoning them are available in the Necronomicon.
