### ISSUE TITLE
By the gods problem with abysslecraft

### ISSUE THREAD

**Issue by EternalOne11** [Shinoow/By-The-Gods#7]
#### Intro:

This template is intended for bug reports. If you're not posting a bug report, you can remove all of the text that makes up the template. If you are reporting a bug, and you choose not to use this template, your issue will be closed. You may now delete this section and continue on with the report.

#### Description:

If this bug occurs in a modpack, please report this to the modpack author. Otherwise delete this line and add your description here.

#### Crash report:

[pastebin/gist/etc link here if the bug results in a crash, leave line empty otherwise]
https://paste.dimdev.org/pupuxebemi.mccrash (from summoning cathulu)
https://paste.dimdev.org/cocosiveti.mccrash  (The old one that you summon with fish and prismerine) Forgot the name
----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft:
- Forge:
- By The Gods:
- AbyssalCraft:

#### Latest log file for when the issue was present:

[pastebin/gist/etc link here]

**Comment by EternalOne11** [comment]
forge version 14.23.5.2838
Minecraft 1.12.2
by the gods 1.0.1
abysslcraft  1.9.8

**Comment by Shinoow** [comment]
First crash looks like the one in #4, no idea what the second is caused by.
Please use the template properly in the future.
